spring.application.name=Vehicle Rental System

server.port=8081

# Database Config (H2 in MySQL mode)
spring.datasource.url=jdbc:h2:mem:rent_db;MODE=MySQL;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# Initialize database schema and data automatically
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# Display SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
